# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run test:unit
    - run: npm run test:acceptance
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: artifacts

  publish-test-results:
    name: "Publish Test Results"
    needs: test
    runs-on: ubuntu-latest

    # the test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        with:
          check_name: Unit Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: junit.unit.xml

      - name: Publish Acceptance Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        with:
          check_name: Acceprance Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: junit.acceptance.xml
