# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test & Publish

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: "Test & Publish"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run test:unit
      - run: npm run test:acceptance
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: artifacts
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: "Run acceptance tests against published package"
        run: SANDBOX_ENVIRONMENT=PRODUCTION npm run test:acceptance

  publish-test-results:
    name: "Publish Test Results"
    needs: test
    runs-on: ubuntu-latest

    # the test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-results

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        with:
          check_name: Unit Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: junit.unit.xml

      - name: Publish Acceptance Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        with:
          check_name: Acceptance Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: junit.acceptance.xml
