# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test & Publish

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: "Test & Publish"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run test:unit
      - run: npm run test:acceptance:local
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: nick-invision/retry@v2
        env:
          INPUT_TOKEN: ''
        with:
          timeout_seconds: 30
          max_attempts: 2
          retry_on: error
          command: npm run test:acceptance:production
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: artifacts
      - name: Push to netlify branch to trigger a demo site deploy
        run: |
          git checkout -b netlify
          git push origin netlify:netlify

  publish-test-results:
    name: "Publish Test Results"
    needs: test
    runs-on: ubuntu-latest

    # the test job might be skipped, we don't need to run this job then
    if: success() || failure()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-results

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        with:
          check_name: Unit Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: junit.unit.xml

      - name: Publish Local Acceptance Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        with:
          check_name: Local Acceptance Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: junit.acceptance.local.xml

      - name: Publish Production Acceptance Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        with:
          check_name: Production Acceptance Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: junit.acceptance.production.xml
